apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedSC
metadata:
  name: allowed-stoarge-classes
spec:
  match:
    namespaces:
    - "default"
  parameters:
    storageClassWhiteList:
    - standard
    - testing
    - awsebscsiprovisioner
