apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DataSyncTest
metadata:
  name: datasynctestconstraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - test 
  parameters:
