apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedGroups
metadata:
  name: allowedgroups 
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["*"]
    namespaces:
      - "kube-system"
    scope: Namespaced  
  parameters:
    allowedgroupslist:
      - oidc:mathematicians
