apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedRepos
metadata:
  name: allowedrepos 
spec:
  parameters:
    allowedreposlist:
      - mesosphere 
      - quay.io
    allowednamespacelist:
      - kubeaddons
      - kube-system
