apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DataSyncTest
metadata:
  name: datasynctestconstraint
spec:
  match:
    kinds:
      - apiGroups: ["extensions"]
        apiVersions: ["v1beta1"]
        kinds: ["Ingress"]
    namespaces:
      - ingresstest 
  parameters:
