---
apiVersion: v1
kind: Namespace
metadata:
  name: ingresstest
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: ingresstest
  namespace: ingresstest
spec:
  rules:
  - host: mytest.d2iq.com
    http:
      paths:
      - path: /
        backend:
          serviceName: test
          servicePort: 8080
