apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HttpSendTest
metadata:
  name: httpsendtestconstraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - sample 
  parameters:
