---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test","creationTimestamp":null},"spec":{},"status":{}}
  name: test

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test
spec:
  containers:
  - image: busybox:1.28.4
    name: mybusy
    command: ["/bin/sh","-c","sleep 100000"]
