apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    run: testdeploy
  name: testdeploy
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: testdeploy
    spec:
      containers:
      - image: nginx:alpine
        name: testdeploy
        resources: {}
      restartPolicy: Always
status: {}
