apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictVolumeTypes
metadata:
  name: restrict-volume-types
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - test 
  parameters:
    userlist:
    - "abcd"
    - "def"
    - "kubernetes-admi"
    volumetypelist:
    - "emptyDir"
